# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Corpora360' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Corpora360
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'SwiftyJSON'
  target 'Corpora360Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
